menu:
- {name: 'Sobre', url: 'sobre.html'}
- {name: 'Arquivo', url: 'arquivo.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope',   link: 'mailto:davidamaral101@gmail.com'}
- {icon: 'github',     link: 'https://www.github.com/pingarelho'}
- {icon: 'rss-square', link: '/feed.xml'}

# Customize site text
pagination:
  next_page: 'Mais antigo'
  previous_page: 'Mais recente'
